services:
  php-app:
    build:
      context: .
    container_name: php-app
    restart: unless-stopped
    init: true
    # Expose port 8000 for Laravel's built-in server
    ports:
      - "8000:8000"
    # Use the .env file for Laravel environment configuration
    env_file:
      - ./.env
    depends_on:
      - mysql-db
    networks:
      - appnet
    # The app runs as a non-root user as per Dockerfile

  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  mysql-data:
    # Persistent storage for MySQL database
